/**
 * AXO NETWORKS
 * Enterprise Role Permission Matrix
 */

const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  BUYER: "BUYER",
  SUPPLIER: "SUPPLIER",
};

const ROLE_PERMISSIONS = {
  SUPER_ADMIN: ["*"],

  ADMIN: [
  "VIEW_USERS",
  "MANAGE_USERS",
  "VIEW_STATS",
  "VIEW_NETWORK_REQUESTS",
  "APPROVE_NETWORK_REQUEST",
  "REJECT_NETWORK_REQUEST",
  "VIEW_PO",
  "FORCE_PO_ACTION",
  "VIEW_DASHBOARD",
  "VIEW_ANALYTICS",
  "VIEW_DISPUTES",
  "RESOLVE_DISPUTE",
],

  BUYER: [
     "VIEW_BUYER_DASHBOARD",
  "CREATE_RFQ",
  "VIEW_RFQ",
  "ACCEPT_QUOTE",
  "REJECT_QUOTE",
  "PAY_MILESTONE",
  "RAISE_DISPUTE",
  ],

  SUPPLIER: [
    "VIEW_OPEN_RFQS",
  "SUBMIT_QUOTE",
  "VIEW_SUPPLIER_POS",
  "ACCEPT_PO",
  "UPDATE_MILESTONE",
  ],
};

module.exports = {
  ROLES,
  ROLE_PERMISSIONS,
};
